- name: DevSecops and MLops
  hosts: local
  connection: local
  vars:
    COURSE: "DevSecOps and MLOps"
    DURATION: "8 weeks"
    TRAINER: "Jane Smith"
  tasks:
  - name: Display course information
    debug:
      msg: "Course: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"
  - name: Display course information from second half
    vars:
      COURSE: "Advanced MLOps"
    debug:
      msg: "Course: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"